name: Monitor Strony Gov.pl

on:
  schedule:
    # Uruchamiaj 3 razy dziennie
    - cron: '0 8,13,18 * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pobierz kod repozytorium
        uses: actions/checkout@v4  # Zmieniono z v3 na v4

      - name: Konfiguracja Pythona
        uses: actions/setup-python@v5  # Zmieniono z v4 na v5
        with:
          python-version: '3.11' # Przy okazji podnieśliśmy wersję Pythona na nowszą

      - name: Instalacja bibliotek
        run: pip install requests beautifulsoup4

      - name: Uruchom bota
        run: python bot.py
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      
  
